[project]
name = "microscopi"
version = "0.10.0-dev"
description = "Digital microscope measurement tool"
authors = [{name = "Jordi Orts"}]
license = {text = "MIT"}
requires-python = ">=3.9"

[project.scripts]
microscopi = "microscopi.app:main"
